name: GCC Build

on:
  push:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        working-directory: ./Streamable
        run: nuget restore

      - name: Build & Run Streamable
        working-directory: ./Streamable
        run: |
          msbuild /m /p:Configuration=Release /p:Platform=x64
          x64\Release\Streamable.exe

      - uses: actions/upload-artifact@master
        with:
          name: Streamable.hpp
          path: nuget

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/download-artifact@master
        with:
          name: Streamable.hpp
          path: nuget

      - name: Install VALID GCC Version
        run: sudo apt install -y g++-12

      - name: Build & Run Tests
        run: |
          g++-12 -Wall -Wextra -Wpedantic -Wdisabled-optimization -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Wmissing-include-dirs -Wnull-dereference -Woverloaded-virtual -Wpointer-arith -Wshadow -Wswitch-enum -Wvla -std=c++20 -I./Shared -I./nuget -ITests Tests/pch.cpp Tests/Main.cpp -o tests
          ./tests
