name: Purge Artifacts

on:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  purge-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GH_TOKEN_PA }}
          expire-in: 0
